
name: Deploy MERN Stack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Node.js for both client and backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and build the client (React)
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
          npm run build

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Build Docker images
      - name: Build and Tag Docker Images
        run: |
          docker build -t my-mern-client ./client
          docker build -t my-mern-backend ./backend

      # Run Docker Compose to start both services
      - name: Deploy Services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

     
